# -*- coding: utf-8 -*-
"""Magic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kwZNGSFC-GIC1d0JG5_N4UFKm8XB8Iek
"""

import tensorflow as ts
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

cols = ["fLength", "fWidth", "fSize", "fConc", "fConc1", "fAsym", "fM3Long", "fM3Trans", "fAlpha", "fDist", "class"]
df = pd.read_csv("magic04.data", names = cols)

df['class'] = (df['class'] == 'g').astype(int)
df.head()

for label in cols[:-1]:
  plt.hist(df[df['class'] == 1][label], color="blue", label="gamma", alpha=0.7, density= True)  #get the labels of the rows with 1
  plt.hist(df[df['class'] == 0][label], color="blue", label="gamma", alpha=0.7, density= True)
  plt.title(label)
  plt.ylabel("Probability")
  plt.xlabel(label)
  plt.legend()
  plt.show()